<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew C. Nowlin">
<meta name="author" content="Aaron Sparks">

<title>Behaving Sustainably: Cultural Cognition, Environmental Orientation, and Pro-Environmental Behavior</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="cc-behave_files/libs/clipboard/clipboard.min.js"></script>
<script src="cc-behave_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="cc-behave_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="cc-behave_files/libs/quarto-html/popper.min.js"></script>
<script src="cc-behave_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cc-behave_files/libs/quarto-html/anchor.min.js"></script>
<link href="cc-behave_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cc-behave_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cc-behave_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cc-behave_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cc-behave_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="cc-behave_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="cc-behave_files/libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="cc-behave.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="cc-behave.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Behaving Sustainably: Cultural Cognition, Environmental Orientation, and Pro-Environmental Behavior</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>

    <div class="quarto-title-meta-contents">
    <p class="author">Matthew C. Nowlin <a href="mailto:matthew.nowlin@uta.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Political Science, University of Texas at Arlington
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Aaron Sparks </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of North Carolina – Chapel Hill
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

    
  
  
  </div>



</header>


<p><strong>Abstract</strong>: Scholars has long noted an “attitude-behavior gap” which reflects an incomplete understanding of how values and beliefs translate into pro-environmental action. This study develops and tests a conceptual model in which cultural worldviews along grid (hierarchy-egalitarianism) and group (individualism-communitarianism) dimensions shape environmental orientations, which in turn drive pro-environmental behavior. Environmental orientation is treated as having a cognitive component, measured by the New Ecological Paradigm (NEP), and an affective component, measured by the Connectedness to Nature Scale (CNS). Using survey data from 501 US adults collected online in July 2017, we estimate a Structural Equation Model (SEM) to test direct, indirect, and mediated relationships among cultural worldviews, the NEP, the CNS, and a 12-item self-reported behavior scale. Results showed hierarchical individualists held weaker ecological worldviews, while egalitarian communitarians held stronger ecological worldviews and felt more connected to nature. Both the NEP and CNS were positively associated with behavior, with the CNS showing the stronger relationship. Cultural worldviews had no significant direct effect on behavior, rather their influence operated entirely through environmental orientations. These findings indicate that cultural worldviews shape pro-environmental behavior indirectly, mediated by cognitive and especially affective environmental orientations, helping to explain part of the attitude-behavior gap.</p>
<p><strong>Keywords</strong>: Pro-environmental behaviors; cultural cognition; ecological worldview; connected to nature</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Achieving environmentally sustainable outcomes likely requires some behavioral changes at the individual, community, and societal levels. However, not all individuals are equally likely to engage in pro-environmental behaviors, and understanding the psychological and cultural factors that drive these behaviors is important for enhancing sustainability. Environmental behaviors are widely studied <span class="citation" data-cites="zhuBibliometricVisualAnalysis2021">(<a href="#ref-zhuBibliometricVisualAnalysis2021" role="doc-biblioref">Zhu, Tong, and Song 2021</a>)</span>, and scholars of environmental psychology often lament the so-called ‘attitude-behavior’ gap wherein environmental attitudes do not explain very much of the variance in environmental behavior <span class="citation" data-cites="sternNewEnvironmentalTheories2000 kollmussMindGapWhy2002 giffordPersonalSocialFactors2014">(<a href="#ref-giffordPersonalSocialFactors2014" role="doc-biblioref">Gifford and Nilsson 2014</a>; <a href="#ref-kollmussMindGapWhy2002" role="doc-biblioref">Kollmuss and Agyeman 2002</a>; <a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>)</span>. If people care strongly about the environment, why do they not act in a more sustainable way? The attitude-behavior gap is not because people are hypocrites but because researchers do not yet have a complete attitude-behavior model <span class="citation" data-cites="kaiserOffsettingBehavioralCosts2021">(<a href="#ref-kaiserOffsettingBehavioralCosts2021" role="doc-biblioref">Kaiser, Kibbe, and Hentschke 2021</a>)</span>.</p>
<p>To understand how environmental attitudes influence behaviors, scholars often use approaches such as the Value-Belief-Norm (VBN) framework, where higher-order values shape second-order beliefs that, in turn, influence behaviors <span class="citation" data-cites="canlasMoreTwentyYears2022 sternNewEnvironmentalTheories2000 sternValueBeliefNormTheorySupport1999 vysevkovaExplainingSupportEnvironmental2026">(<a href="#ref-canlasMoreTwentyYears2022" role="doc-biblioref">Canlas, Karpudewan, and Khan 2022</a>; <a href="#ref-sternValueBeliefNormTheorySupport1999" role="doc-biblioref">Stern et al. 1999</a>; <a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>; <a href="#ref-vysevkovaExplainingSupportEnvironmental2026" role="doc-biblioref">Vysevkova et al. 2026</a>)</span>. Higher-order values form a cognitive foundation that influences how information about the world is processed and understood across multiple issues <span class="citation" data-cites="ripbergerCulturalTheoryMeasurement2014">(<a href="#ref-ripbergerCulturalTheoryMeasurement2014" role="doc-biblioref">Ripberger et al. 2014</a>)</span>. When considering environmental behaviors, the second-order values involve environmental cognition, such as views about the relationship of humans to the natural world and how information about the environment is understood <span class="citation" data-cites="sternValueBasisEnvironmental1994 henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012</a>; <a href="#ref-sternValueBasisEnvironmental1994" role="doc-biblioref">Stern and Dietz 1994</a>)</span>. In addition to environmental cognition, individuals also have affective feelings about the environment <span class="citation" data-cites="gkargkavouziMultidimensionalMeasureEnvironmental2019 mayerConnectednessNatureScale2004">(<a href="#ref-gkargkavouziMultidimensionalMeasureEnvironmental2019" role="doc-biblioref">Gkargkavouzi, Halkos, and Matsiori 2019</a>; <a href="#ref-mayerConnectednessNatureScale2004" role="doc-biblioref">Mayer and Frantz 2004</a>)</span>. Together, environmental cognition and affective feelings form an environmental orientation that shapes environmental behaviors. However, to develop a complete attitude-behavior model, it is important to understand the various links in the chain, including the higher-order values and cognition that inform environmental orientations. Of note, the cultural worldviews measured by cultural cognition have been shown to shape environmental orientations <span class="citation" data-cites="nowlinEnvironmentalPolicymakingEra2019">(<a href="#ref-nowlinEnvironmentalPolicymakingEra2019" role="doc-biblioref">Nowlin 2019</a>)</span>.</p>
<p>Cultural cognition was developed as a tool to measure how cultural values shape beliefs about risk <span class="citation" data-cites="kahanCultureIdentityProtectiveCognition2007">(e.g., <a href="#ref-kahanCultureIdentityProtectiveCognition2007" role="doc-biblioref">Kahan et al. 2007</a>)</span>. It is based on cultural theory and its conceptualization of worldviews <span class="citation" data-cites="kahanCulturalCognitionConception2012 douglasRiskCultureEssay1982">(<a href="#ref-douglasRiskCultureEssay1982" role="doc-biblioref">Douglas and Wildavsky 1982</a>; <a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>)</span>. Cultural theory addresses how cultural values influence people’s perceptions of and responses to risk. By measuring an individual’s cultural values, we may be able to predict how they will perceive and respond to risks associated with certain activities or products. We are interested in how cultural cognition shapes views toward environmental issues and how these views shape behavior. Cultural worldviews and their subsequent risk perceptions are likely strong drivers of environmental orientation because environmental problems typically involve elements of risk or harm to the environment.</p>
<p>The cultural worldviews associated with cultural cognition are measured in two dimensions, a grid dimension (egalitarianism-hierarchy) and a group dimension (communitarianism-individualism). In general, those who are more egalitarian and communitarian are more concerned about environmental risks than those who are more hierarchical and individualist. Therefore, it is expected that individuals high in egalitarianism and communitarianism should engage in pro-environmental behaviors to mitigate risks to the natural environment. However, previous research has shown only a weak correlation between egalitarianism, communitarianism, and pro-environmental behavior <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(<a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>. Therefore, cultural cognition shapes how individuals think and process information about issues but may not directly influence behaviors.</p>
<p>In this paper, we develop a conceptual framework that accounts for both the cognitive and affective influences on pro-environmental behavior. Specifically, we posit that higher-order beliefs, drawn from cultural cognition <span class="citation" data-cites="kahanCulturalCognitionConception2012 kahanCulturalCognitionPublic2006 kahanPolarizingImpactScience2012">(<a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>; <a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>; <a href="#ref-kahanCulturalCognitionPublic2006" role="doc-biblioref">Kahan and Braman 2006</a>)</span>, inform environmental orientations <span class="citation" data-cites="henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012</a>)</span>, which in turn influence both public and private behavior. Drawing from <span class="citation" data-cites="henryUnderstandingEnvironmentalCognition2012">Henry and Dietz (<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">2012</a>)</span>, we use the New Ecological Paradigm (NEP) as our measure of environmental cognition and the Connectedness to Nature Scale (CNS) as the affective element of environmental orientation. Previous work failed to find that cultural cognition influences environmental behavior; however, it has been found to influence environmental cognition using the NEP <span class="citation" data-cites="nowlinEnvironmentalPolicymakingEra2019">(<a href="#ref-nowlinEnvironmentalPolicymakingEra2019" role="doc-biblioref">Nowlin 2019</a>)</span>. Therefore, we hypothesize that environmental orientations mediate the relationship between cultural cognition and behavior.</p>
<p>Overall, we found that egalitarian communitarians hold an ecological worldview and feel more connected to nature. However, hierarchical individualists are less concerned about the environment than those with other worldviews. Additionally, we find that ecological worldviews are associated with feeling connected to nature, and that both worldviews and affective nature connection are associated with an increase in self-reported pro-environmental behaviors. Finally, we find that environmental orientations mediate the relationship between cultural worldviews and behaviors, meaning that cultural worldviews play an important, but indirect, role in environmental behaviors.</p>
</section>
<section id="cognition-environmental-orientations-and-pro-environmental-behavior" class="level1">
<h1>Cognition, Environmental Orientations, and Pro-Environmental Behavior</h1>
<p>The process through which values and beliefs impact behavior is often understood as a process where higher-order, antecedent values influence second-order beliefs, which in turn influence behavior <span class="citation" data-cites="stegGeneralAntecedentsPersonal2011 dietzEnvironmentalValues2005">(<a href="#ref-dietzEnvironmentalValues2005" role="doc-biblioref">Dietz, Fitzgerald, and Shwom 2005</a>; <a href="#ref-stegGeneralAntecedentsPersonal2011" role="doc-biblioref">Steg et al. 2011</a>)</span>. One of the leading frameworks that adopts this approach is the Value-Belief-Norm (VBN) framework <span class="citation" data-cites="sternValueBeliefNormTheorySupport1999 sternNewEnvironmentalTheories2000">(<a href="#ref-sternValueBeliefNormTheorySupport1999" role="doc-biblioref">Stern et al. 1999</a>; <a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>)</span>. In brief, the VBN posits that underlying values inform broad environmental orientations that activate norms that, in turn, support pro-environmental behavior. VBN involves a sequential chain that goes from values to beliefs to behavior. Therefore, values inform attitudes, which in turn inform behavior.</p>
<p>As noted, the VBN framework moves from values to beliefs to norms to pro-environmental behaviors. The values that have been identified and applied include biospheric, altruistic, and egoistic values <span class="citation" data-cites="canlasMoreTwentyYears2022 sternNewEnvironmentalTheories2000">(<a href="#ref-canlasMoreTwentyYears2022" role="doc-biblioref">Canlas, Karpudewan, and Khan 2022</a>; <a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>)</span>. Biospheric values are associated with concern for the environment, altruistic values involve concern for others, and egoistic values shape concern for self <span class="citation" data-cites="fornaraExtendedValueBeliefNormTheory2020">(<a href="#ref-fornaraExtendedValueBeliefNormTheory2020" role="doc-biblioref">Fornara et al. 2020</a>)</span>. In general, biospheric and altruistic values are associated with an ecological worldview, whereas egoistic values are not. Beliefs are grounded in ecological worldviews, which are typically operationalized using the New Ecological Paradigm (NEP) measure <span class="citation" data-cites="chenExaminationValuebeliefnormTheory2015 fornaraExtendedValueBeliefNormTheory2020 slimakPersonalValuesBeliefs2006 sternValueBeliefNormTheorySupport1999">(<a href="#ref-chenExaminationValuebeliefnormTheory2015" role="doc-biblioref">Chen 2015</a>; <a href="#ref-fornaraExtendedValueBeliefNormTheory2020" role="doc-biblioref">Fornara et al. 2020</a>; <a href="#ref-slimakPersonalValuesBeliefs2006" role="doc-biblioref">Slimak and Dietz 2006</a>; <a href="#ref-sternValueBeliefNormTheorySupport1999" role="doc-biblioref">Stern et al. 1999</a>)</span>. Additional beliefs include awareness of consequences (AC) and ascription of responsibility (AR), which are active norms involving a sense of obligation to act <span class="citation" data-cites="sternNewEnvironmentalTheories2000">(<a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>)</span>. The behaviors identified include private consumption-based behaviors, public-facing activism, and support for environmental policies <span class="citation" data-cites="sternValueBeliefNormTheorySupport1999">(<a href="#ref-sternValueBeliefNormTheorySupport1999" role="doc-biblioref">Stern et al. 1999</a>)</span>. VBN is widely used <span class="citation" data-cites="canlasMoreTwentyYears2022 vysevkovaExplainingSupportEnvironmental2026">(<a href="#ref-canlasMoreTwentyYears2022" role="doc-biblioref">Canlas, Karpudewan, and Khan 2022</a>; <a href="#ref-vysevkovaExplainingSupportEnvironmental2026" role="doc-biblioref">Vysevkova et al. 2026</a>)</span> across multiple contexts, including climate mitigation behaviors in Taiwan <span class="citation" data-cites="chenExaminationValuebeliefnormTheory2015">(<a href="#ref-chenExaminationValuebeliefnormTheory2015" role="doc-biblioref">Chen 2015</a>)</span>, energy conservation <span class="citation" data-cites="yeboahExplainingEnergyConservation2016">(<a href="#ref-yeboahExplainingEnergyConservation2016" role="doc-biblioref">Yeboah and Kaplowitz 2016</a>)</span>, biodiversity in Europe <span class="citation" data-cites="fornaraExtendedValueBeliefNormTheory2020 riepeValuesBeliefsNorms2021">(<a href="#ref-fornaraExtendedValueBeliefNormTheory2020" role="doc-biblioref">Fornara et al. 2020</a>; <a href="#ref-riepeValuesBeliefsNorms2021" role="doc-biblioref">Riepe et al. 2021</a>)</span>, and perceptions of environmental risk <span class="citation" data-cites="slimakPersonalValuesBeliefs2006">(<a href="#ref-slimakPersonalValuesBeliefs2006" role="doc-biblioref">Slimak and Dietz 2006</a>)</span>.</p>
<p>A similar set of assumptions inform an understanding of belief systems developed by policy scholars using the Advocacy Coalition Framework (ACF) <span class="citation" data-cites="nohrstedtAdvocacyCoalitionFramework2023 sabatierPolicyChangeLearning1993 henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012</a>; <a href="#ref-nohrstedtAdvocacyCoalitionFramework2023" role="doc-biblioref">Nohrstedt et al. 2023</a>; <a href="#ref-sabatierPolicyChangeLearning1993" role="doc-biblioref">Sabatier and Jenkins-Smith 1993</a>)</span>. With this approach, belief systems are interrelated beliefs made up of three different types, including deep core, policy core, and secondary beliefs. Deep core beliefs are the broadest in scope and are fundamental beliefs that inform attitudes toward multiple issues. They tend to be stable, play a role in how issues are understood, and influence reasoning about issues <span class="citation" data-cites="kahanPolarizingImpactScience2012 nohrstedtAdvocacyCoalitionFramework2023">(<a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>; <a href="#ref-nohrstedtAdvocacyCoalitionFramework2023" role="doc-biblioref">Nohrstedt et al. 2023</a>)</span>. Biospheric, altruistic, and egoistic values, as well as political ideology, can be seen as examples of deep core beliefs. Next, are policy core beliefs, which are beliefs about particular issues. Environmental orientations would be akin to policy core beliefs. Finally, secondary aspects are the narrowest in scope and include beliefs about how to best achieve the goals outlined in policy core beliefs. We aim to build on previous work that noted a connection between the VBN and the ACF <span class="citation" data-cites="henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012</a>)</span>.</p>
<p>In developing our approach, we draw from both VBN and the ACF by positing a sequential chain and a hierarchical ordering of values, beliefs, and attitudes that lead from abstract values to concrete actions. Specifically, we note that deep core beliefs inform environmental orientations that, in turn, make pro-environmental behaviors more (or less) likely. In addition, we separate beliefs that shape <em>cognition</em> from the affective and identity elements of environmental orientations. We note that the role of cognition has not been well developed in approaches to understanding environmental behaviors, despite the importance that the way worldviews shape information processing has on midstream beliefs and downstream behaviors <span class="citation" data-cites="liobikieneImportanceEnvironmentalKnowledge2019 ripbergerCulturalTheoryMeasurement2014">(<a href="#ref-liobikieneImportanceEnvironmentalKnowledge2019" role="doc-biblioref">Liobikienė and Poškus 2019</a>; <a href="#ref-ripbergerCulturalTheoryMeasurement2014" role="doc-biblioref">Ripberger et al. 2014</a>)</span>. Our measure of deep core beliefs is cultural cognition, which, as the name implies, involves deeply rooted values and beliefs that influence cognition. For environmental orientations, we draw on environmental cognition, which is “the way individuals structure their thinking about environmental issues and associated political actions” <span class="citation" data-cites="henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012, 238</a>)</span>. We argue that environmental orientations contain both cognitive and affective elements. Deep core beliefs influence both the cognitive and affective aspects of environmental orientations. Finally, deep core beliefs and environmental orientations influence pro-environmental behaviors; however, it is not clear whether deep core beliefs influence behaviors directly <span class="citation" data-cites="markleUnderstandingProEnvironmentalBehavior2019">(<a href="#ref-markleUnderstandingProEnvironmentalBehavior2019" role="doc-biblioref">Markle 2019</a>)</span> or indirectly <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(<a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>. However, the affective element of environmental orientations tends to have the most direct influence on behaviors <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021 mackayPeopleWhoFeel2019">(<a href="#ref-mackayPeopleWhoFeel2019" role="doc-biblioref">Mackay and Schmitt 2019</a>; <a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>.</p>
<section id="deep-core-beliefs-cultural-cognition" class="level2">
<h2 class="anchored" data-anchor-id="deep-core-beliefs-cultural-cognition">Deep Core Beliefs: Cultural Cognition</h2>
<p>For our measure of deep core beliefs we use cultural cognition. Cultural cognition is derived from the cultural theory of risk developed by Mary Douglas and Aaron Wildavsky <span class="citation" data-cites="douglasRiskCultureEssay1982 thompsonCulturalTheory1990 kahanCulturalCognitionConception2012">(<a href="#ref-douglasRiskCultureEssay1982" role="doc-biblioref">Douglas and Wildavsky 1982</a>; <a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>; <a href="#ref-thompsonCulturalTheory1990" role="doc-biblioref">Thompson, Ellis, and Wildavsky 1990</a>)</span>. Cultural theory (CT) has been identified as a leading way to conceptualize and measure deep core beliefs <span class="citation" data-cites="ripbergerCulturalTheoryMeasurement2014">(<a href="#ref-ripbergerCulturalTheoryMeasurement2014" role="doc-biblioref">Ripberger et al. 2014</a>)</span>. In brief, CT posits that social structures and relationships are represented by two dimensions, including a grid dimension and a group dimension. Four competing cultural worldviews are possible based on their positioning in the grid and group dimensional space. The grid dimension represents preferred social structures regarding the roles that one plays in society and the rules by which one must abide. The group dimension represents the importance of cohesive social units and the well-being of the broader community. The original formulation of CT produces four cultural worldviews based on the relative positions on the grid and group dimensions, including hierarchy (high grid, high group), egalitarianism (low grid, high group), individualism (low grid, and low group), and fatalism (high grid, low group).</p>
<p>Cultural worldviews provide a foundational set of deep core beliefs that inform beliefs about specific policy issues (i.e., policy core beliefs), societal controversies, and risks, among other beliefs <span class="citation" data-cites="nowlinEnvironmentalPolicymakingEra2019 ripbergerCulturalTheoryMeasurement2014 jenkins-smithBeliefSystemContinuity2014 sotirovCognitiveTheoryShifting2016">(<a href="#ref-jenkins-smithBeliefSystemContinuity2014" role="doc-biblioref">Jenkins-Smith et al. 2014</a>; <a href="#ref-nowlinEnvironmentalPolicymakingEra2019" role="doc-biblioref">Nowlin 2019</a>; <a href="#ref-ripbergerCulturalTheoryMeasurement2014" role="doc-biblioref">Ripberger et al. 2014</a>; <a href="#ref-sotirovCognitiveTheoryShifting2016" role="doc-biblioref">Sotirov and Winkel 2016</a>)</span>. In the context of cultural worldviews, perceptions of risk are based on the degree to which they undermine or threaten the preferred social order within each worldview. Several studies have shown a connection between cultural worldviews and risk perceptions associated with a host of environmental issues <span class="citation" data-cites="xueCulturalWorldviewsEnvironmental2014">(see <a href="#ref-xueCulturalWorldviewsEnvironmental2014" role="doc-biblioref">Xue et al. 2014</a>)</span>, including fracking <span class="citation" data-cites="boudetFrackingControversyCommunication2014">(<a href="#ref-boudetFrackingControversyCommunication2014" role="doc-biblioref">Boudet et al. 2014</a>)</span>, nuclear waste <span class="citation" data-cites="jenkins-smithIdeologyCultureRisk1994">(<a href="#ref-jenkins-smithIdeologyCultureRisk1994" role="doc-biblioref">Jenkins-Smith and Smith 1994</a>)</span>, renewable energy <span class="citation" data-cites="tumlisonWhatExplainsLocal2018">(<a href="#ref-tumlisonWhatExplainsLocal2018" role="doc-biblioref">Tumlison et al. 2018</a>)</span>, geoengineering <span class="citation" data-cites="kahanGeoengineeringClimateChange2015">(<a href="#ref-kahanGeoengineeringClimateChange2015" role="doc-biblioref">Kahan et al. 2015</a>)</span>, natural resource management <span class="citation" data-cites="quanCognitionConservationApplying2025">(<a href="#ref-quanCognitionConservationApplying2025" role="doc-biblioref">Quan, Song, and Nguyen 2025</a>)</span>, high-voltage power lines <span class="citation" data-cites="moyerCulturalPredispositionsSpecific2019">(<a href="#ref-moyerCulturalPredispositionsSpecific2019" role="doc-biblioref">Moyer and Song 2019</a>)</span>, and climate change <span class="citation" data-cites="jonesLeadingWayCompromise2011 kahanPolarizingImpactScience2012 nowlinCulturalTheoryPartisanship2020 nowlinWhoShouldMore2022">(<a href="#ref-jonesLeadingWayCompromise2011" role="doc-biblioref">Jones 2011</a>; <a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>; <a href="#ref-nowlinWhoShouldMore2022" role="doc-biblioref">Nowlin 2022</a>; <a href="#ref-nowlinCulturalTheoryPartisanship2020" role="doc-biblioref">Nowlin and Rabovsky 2020</a>)</span>, among others.</p>
<p>Cultural cognition is based on CT and its cultural worldviews but makes two important distinctions. The first is its focus on the social and psychological mechanisms that underlie how worldviews influence opinions on contested political and policy issues. Cultural commitments occur prior to facts, “in the cognitive sense that what citizens believe about the empirical consequences of [controversial] policies <em>derives</em> from their cultural worldviews” <span class="citation" data-cites="kahanCulturalCognitionPublic2006">(<a href="#ref-kahanCulturalCognitionPublic2006" role="doc-biblioref">Kahan and Braman 2006, 148</a>)</span>. Individuals rely on five mechanisms to ensure that their positions on issues are congruent with their cultural worldviews. These mechanisms include: 1) <em>cultural identity-protective cognition</em>, where individuals conform their beliefs to those in their “group” that share cultural values; 2) <em>culturally biased assimilation and cultural polarization</em>, which involves selective attention to worldview-confirming information and balanced information that tends to drive people of opposing worldviews further apart rather than together; 3) <em>cultural availability</em>, which occurs as worldview-confirming events and experts are more readily noticed, credited, and recalled; 4) <em>cultural credibility heuristic</em>, when people trust sources whose apparent values match their own; and 5) <em>cultural-identity affirmation</em>, which has been shown when framing information alongside an identity-affirming rather than identity-threatening policy solution makes people more receptive to the underlying facts <span class="citation" data-cites="kahanCulturalCognitionConception2012">(<a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>)</span>. Together, these mechanisms account for the cognitive aspect of cultural cognition.</p>
<p>The second distinction between cultural cognition and CT is how cultural worldviews are measured empirically. As noted, the CT worldviews are based on the placement on the grid and group dimensions, and worldviews are a result of placement on both. However, cultural cognition conceives grid and group as two orthogonal dimensions, with worldviews identified as being high or low on each dimension rather than a combination of the dimensions. Those high on the grid dimension are called hierarchical, as they prefer a society with well-defined roles and clear lines of authority, whereas those low on the grid dimension are termed egalitarian, as they value a social order based on an equal sharing of power and resources. Communitarianism is the worldview that is high on the group dimension and represents a preference for a collectivist society. Finally, individualism is low on the group dimension, preferring increased individual autonomy and responsibility <span class="citation" data-cites="kahanCulturalCognitionConception2012 kahanCulturalCognitionPublic2006 kahanPolarizingImpactScience2012">(<a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>; <a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>; <a href="#ref-kahanCulturalCognitionPublic2006" role="doc-biblioref">Kahan and Braman 2006</a>)</span>.</p>
<p>Studies using cultural cognition often compare the risk perceptions of hierarchical individualists, those high on the grid dimension and low on the group dimension, to their reverse, egalitarian communitarians who are low on grid and high on the group dimension. The differences in risk perception between these pairings are significant for risks related to the environment, abortion, and guns <span class="citation" data-cites="kahanCultureIdentityProtectiveCognition2007">(<a href="#ref-kahanCultureIdentityProtectiveCognition2007" role="doc-biblioref">Kahan et al. 2007</a>)</span>. For environmental risks specifically, communitarianism, with its concern about collective well-being and egalitarianism, with its concern about the negative impacts of concentrated power tend to see threats to the natural world as a large risk. Hierarchs believe that natural resources can be well managed by experts and individualism supports the use of natural resources in private enterprise, and therefore hierarchy and individualism tend not to be concerned about environment harm. Studies have shown the differences between hierarchical individualists and egalitarian communitarians on climate change <span class="citation" data-cites="kahanPolarizingImpactScience2012">(<a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>)</span> and water supply risk <span class="citation" data-cites="overdevestUsingCulturalCognition2013">(<a href="#ref-overdevestUsingCulturalCognition2013" role="doc-biblioref">Overdevest and Christiansen 2013</a>)</span>. In terms of the influence of cultural cognition and pro-environmental behavior, the results are somewhat mixed. One study found that hierarchy and individualism predicted fewer self-reported pro-environment behaviors <span class="citation" data-cites="markleUnderstandingProEnvironmentalBehavior2019">(<a href="#ref-markleUnderstandingProEnvironmentalBehavior2019" role="doc-biblioref">Markle 2019</a>)</span>, whereas another study found no connection between cultural cognition and behavior <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(<a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>.</p>
<p>As a measure of deep core beliefs, cultural cognition will likely have an indirect association with environmental behaviors, meaning that the relationship will be mediated by environmental orientations. Indeed, cultural cognition worldviews, specifically egalitarianism and communitarianism are associated with pro-environmental orientation, specifically the New Ecological Paradigm (NEP) <span class="citation" data-cites="nowlinEnvironmentalPolicymakingEra2019 overdevestUsingCulturalCognition2013">(<a href="#ref-nowlinEnvironmentalPolicymakingEra2019" role="doc-biblioref">Nowlin 2019</a>; <a href="#ref-overdevestUsingCulturalCognition2013" role="doc-biblioref">Overdevest and Christiansen 2013</a>)</span>.</p>
</section>
<section id="new-ecological-paradigm" class="level2">
<h2 class="anchored" data-anchor-id="new-ecological-paradigm">New Ecological Paradigm</h2>
<p>Moving from deep core beliefs to environmental orientations, the first measure of environmental orientations is the New Ecological Paradigm (NEP). The NEP, developed in 1978 <span class="citation" data-cites="dunlapNewEnvironmentalParadigm1978">(<a href="#ref-dunlapNewEnvironmentalParadigm1978" role="doc-biblioref">Dunlap and Van Liere 1978</a>)</span>, is often used in the VBN framework as a measure of environmental beliefs <span class="citation" data-cites="canlasMoreTwentyYears2022">(<a href="#ref-canlasMoreTwentyYears2022" role="doc-biblioref">Canlas, Karpudewan, and Khan 2022</a>)</span>, and has been widely adopted to explain environmental behavior <span class="citation" data-cites="sternNewEnvironmentalTheories2000">(e.g., <a href="#ref-sternNewEnvironmentalTheories2000" role="doc-biblioref">Stern 2000</a>)</span>. Its original development focused on explaining the values associated with environmentalism as an emergent environmental paradigm that challenged the dominant social paradigm. Central to the NEP is the concern about the environment and beliefs about the proper relationship between humans and the natural world <span class="citation" data-cites="sternNewEcologicalParadigm1995">(<a href="#ref-sternNewEcologicalParadigm1995" role="doc-biblioref">Stern, Dietz, and Guagnano 1995</a>)</span>. The NEP was updated in 2000, and the new measure comprises five aspects which are “the reality of the limits to growth, anti-anthropocentrism, the fragility of earth’s balance, rejection of exemptionalism, and the possibility of an ecocrisis” <span class="citation" data-cites="dunlapNewTrendsMeasuring2000">(<a href="#ref-dunlapNewTrendsMeasuring2000" role="doc-biblioref">Dunlap et al. 2000, 432</a>)</span>.</p>
<p>In our approach, we view the NEP as an ecological worldview that encompasses values associated with the environment, and like cultural cognition, works to ensure that an individual’s beliefs about the environment remain congruent with their ecological worldview. As a worldview, the NEP measures the environmental cognition that shapes how the natural world is seen <span class="citation" data-cites="xiaoEcologicalWorldviewCentral2019 ballewSystemsThinkingPathway2019 henryUnderstandingEnvironmentalCognition2012">(<a href="#ref-ballewSystemsThinkingPathway2019" role="doc-biblioref">Ballew et al. 2019</a>; <a href="#ref-henryUnderstandingEnvironmentalCognition2012" role="doc-biblioref">Henry and Dietz 2012</a>; <a href="#ref-xiaoEcologicalWorldviewCentral2019" role="doc-biblioref">Xiao, Dunlap, and Hong 2019</a>)</span>. Similar to how the NEP has been used in the VBN framework, we consider it an environmental orientation that is situated between values and behaviors; however, we argue that, as a worldview, it is a cognitive component of environmental orientations. As a cognition, it influences thinking about environmental issues, shapes other aspects of environmental orientations, and is associated with pro-environmental behaviors <span class="citation" data-cites="derdowskiNewEcologicalParadigm2020">(<a href="#ref-derdowskiNewEcologicalParadigm2020" role="doc-biblioref">Derdowski et al. 2020</a>)</span>.</p>
<p>There are some significant critiques of the NEP. One study applying scale analysis of the NEP based on a random sample of Norwegians found that the scale is not unidimensional, as is often claimed <span class="citation" data-cites="grendstadNewEcologicalParadigm1999">(<a href="#ref-grendstadNewEcologicalParadigm1999" role="doc-biblioref">Grendstad 1999</a>)</span>. In another study, <span class="citation" data-cites="sparksMeasuringProenvironmentalOrientation2022">Sparks, Ehret, and Brick (<a href="#ref-sparksMeasuringProenvironmentalOrientation2022" role="doc-biblioref">2022</a>)</span> criticized the NEP for failing to adequately identify political conservatives who also hold a pro-environment orientation. Most important for our purposes is a study that found the NEP to be a relatively weak predictor of self-reported pro-environmental behavior, accounting for 12% of the variation when compared in the same sample to the Connectedness to Nature Scale and environmentalist identity <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(<a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>. This may be because endorsement of the NEP has decreased over time <span class="citation" data-cites="louMetaanalysisTemporalShifts2022">(<a href="#ref-louMetaanalysisTemporalShifts2022" role="doc-biblioref">Lou et al. 2022</a>)</span>, or it may be that feeling close and connected to nature is more proximate to behavior than more abstract, cognitive worldviews, such as cultural cognition and the NEP.</p>
</section>
<section id="connectedness-to-nature" class="level2">
<h2 class="anchored" data-anchor-id="connectedness-to-nature">Connectedness to Nature</h2>
<p>Our second instrument for measuring environmental orientation is the Connectedness to Nature Scale (CNS) <span class="citation" data-cites="mayerConnectednessNatureScale2004">(<a href="#ref-mayerConnectednessNatureScale2004" role="doc-biblioref">Mayer and Frantz 2004</a>)</span>. The CNS seeks to measure an individual’s emotional connection to nature rather than a cognitive environmental worldview. The CNS is based on the notion that to address environmental problems, people must feel emotionally connected to the non-human community on which they are dependent. The idea is that the current ecological crises are a direct result of humanity losing touch with the broader community in which we live. As we argue, the NEP captures the cognitive element of environmental orientation, and feeling connected to nature captures the affective element.</p>
<p>Research on connectedness to nature consistently suggests that people who feel more psychologically linked to the natural world are more likely to engage in pro-environmental behavior. Two meta-analyses found strong and consistent positive relationships between pro-environmental behavior and connection to nature <span class="citation" data-cites="mackayPeopleWhoFeel2019 whitburnMetaanalysisHumanConnection2020">(<a href="#ref-mackayPeopleWhoFeel2019" role="doc-biblioref">Mackay and Schmitt 2019</a>; <a href="#ref-whitburnMetaanalysisHumanConnection2020" role="doc-biblioref">Whitburn, Linklater, and Abrahamse 2020</a>)</span>. In addition, a psychological connection to nature predicts environmental attitudes and behaviors beyond broader environmental worldview measures, suggesting that connectedness to nature is not just a re-labeling of general environmental concern but a distinct predictor <span class="citation" data-cites="nisbetNatureRelatednessScale2009">(<a href="#ref-nisbetNatureRelatednessScale2009" role="doc-biblioref">Nisbet, Zelenski, and Murphy 2009</a>)</span>. More recent work extends this finding across multiple behavioral domains, including civic action, recycling, household conservation, and consumer choices, which were all predicted by connectedness to nature, whereas policy support and transportation were predicted by environmental concern, which included the NEP <span class="citation" data-cites="gkargkavouziMultidimensionalMeasureEnvironmental2019">(<a href="#ref-gkargkavouziMultidimensionalMeasureEnvironmental2019" role="doc-biblioref">Gkargkavouzi, Halkos, and Matsiori 2019</a>)</span>. One study assessed the role of personality traits in environmental behavior and provided a comparison of the mediation effect of both the NEP and the CNS on environmental behaviors <span class="citation" data-cites="brickUnearthingGreenPersonality2016">(<a href="#ref-brickUnearthingGreenPersonality2016" role="doc-biblioref">Brick and Lewis 2016</a>)</span>. The personality traits of Openness and Conscientiousness were both shown to be positive predictors of environmental behavior. In both cases, the CNS had a stronger mediating effect than the NEP. In other words, the CNS better predicted pro-environmental outcomes.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Finally, the CNS (plus control variables) accounted for 35% of the variance in environmental behaviors<span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(<a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>.</p>
</section>
</section>
<section id="conceptual-model-and-hypotheses" class="level1">
<h1>Conceptual Model and Hypotheses</h1>
<p>Cultural cognition can be thought of as a deep core belief; therefore, it is an antecedent to environmental orientations. Culture-based views of risk and the social-psychological tendencies to protect those views likely precede the development of environment-specific cognition, attitudes, and orientations. Given the mixed evidence, it is unclear whether the connection between cultural cognition and environmental behavior is direct or indirect.</p>
<p>Taking the step from cultural worldviews to environmental orientations, we suggest that environmental orientations contain both a cognitive worldview element that can be measured by the New Ecological Paradigm (NEP) and an affective emotional connection to nature, as measured by the Connectedness to Nature Scale (CNS). As noted, cultural worldviews are an antecedent to environmental orientations. Similarly, we posit that ecological worldviews are an antecedent to connectedness to nature. Finally, environmental orientations are predictive of pro-environmental behaviors.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <a href="#fig-model" class="quarto-xref">Figure&nbsp;1</a> illustrates our conceptual model connecting cognition based on cultural and ecological worldviews, environmental orientations, including both the ecological worldview component and the affective connection to nature component, and pro-environmental behaviors.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Conceptual model tested with the structural equation model: cultural cognition shapes environmental orientation—first the New Ecological Paradigm (NEP) and then the Connectedness to Nature Scale (CNS)—which in turn shapes pro-environmental behavior.
</figcaption>
<div aria-describedby="fig-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cc-behave_files/figure-html/fig-model-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Based on the model shown in <a href="#fig-model" class="quarto-xref">Figure&nbsp;1</a>, we posit several hypotheses regarding the relationships between cultural cognition, the NEP, the CNS, and environmental behavior. Our hypotheses include the sequence approach shown in <a href="#fig-model" class="quarto-xref">Figure&nbsp;1</a>, where cultural worldviews influence ecological worldviews, ecological worldviews influence connectedness to nature, and connectedness to nature influences pro-environmental behaviors. We also have direct hypotheses, where cultural and ecological worldviews are directly associated with behaviors. We expect that:</p>
<blockquote class="blockquote">
<p>H1: Hierarchical-individualists are associated with a <em>decrease</em> in the ecological worldview element of environmental orientation, a <em>decrease</em> in the connected to nature element of environmental orientation, and <em>fewer</em> pro-environmental behaviors</p>
</blockquote>
<blockquote class="blockquote">
<p>H2: Egalitarian-communitarians are associated with an <em>increase</em> in the ecological worldview element of environmental orientation, an <em>increase</em> in the connected to nature element of environmental orientation, and <em>more</em> pro-environmental behaviors</p>
</blockquote>
<blockquote class="blockquote">
<p>H3: Ecological worldviews are associated with an <em>increase</em> in connectedness to nature</p>
</blockquote>
<blockquote class="blockquote">
<p>H4: Both the cognitive and affective elements of environmental orientations are associated with <em>more</em> pro-environmental behaviors</p>
</blockquote>
</section>
<section id="data-and-methods" class="level1">
<h1>Data and Methods</h1>
<p>To examine the relationship between cultural cognition, environmental orientations, and behavior, we draw on a sample of 501 adults living in the US purchased through Survey Sampling Inc.&nbsp;Overall, the sample is largely reflective of the US population in terms of demographics, as 51% of respondents are women, 67% are white, and the average respondent is 44 years of age. Additionally, the average person in our sample had attended some college and reported a household income between $95,001 and 130,000. The survey was administered online in July 2017. The sample size was determined based on cost considerations. Our analysis was not pre-registered.</p>
<section id="measures" class="level2">
<h2 class="anchored" data-anchor-id="measures">Measures</h2>
<p>Our dependent variable is a 12-item scale of self-reported pro-environmental behaviors. The questions were taken from the 2000 Gallup Earth Day Poll. Respondents were given a list of several environmental behaviors and asked, “<em>Which of these, if any, have you, yourself, done in the past year</em>?” Possible responses included, “Yes, have done; No, have not done; No opinion.” Yes, responses were coded as 1, and no/no opinion was coded as 0. For the purposes of analysis, we treated the behavioral measures as observed and added the number of self-reported behaviors together to produce a measure that ranged from 0 (no behaviors) to 12 (all behaviors). <a href="#tbl-behaviors" class="quarto-xref">Table&nbsp;1</a> shows the question wording as well as the mean and sd for each self-reported behavior. We also note the 7 public and 5 private behaviors, but we use the single 0-12 scale for analysis.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div id="tbl-behaviors" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-behaviors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Self-reported pro-environmental behaviors by type (public/private), with means and standard deviations
</figcaption>
<div aria-describedby="tbl-behaviors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-7c9f8346{}.cl-7c9c3a42{font-family:'Helvetica';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c9c3a4c{font-family:'Helvetica';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c9d9478{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7c9d9479{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7c9dad5a{width:4.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad64{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad65{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad66{width:4.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad67{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad6e{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad6f{width:4.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad70{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9dad71{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-7c9f8346"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7c9dad5a"><p class="cl-7c9d9478"><span class="cl-7c9c3a42">Behavior</span></p></th><th class="cl-7c9dad64"><p class="cl-7c9d9478"><span class="cl-7c9c3a42">Type</span></p></th><th class="cl-7c9dad65"><p class="cl-7c9d9479"><span class="cl-7c9c3a42">Mean</span></p></th><th class="cl-7c9dad65"><p class="cl-7c9d9479"><span class="cl-7c9c3a42">SD</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Been active in a group/organization that works to protect the environment</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.19</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.39</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Voted for or worked for candidates because of their environmental positions</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.40</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Contributed money to an environmental, conservation, or wildlife group</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.33</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Contacted a public official about an environmental issue</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.19</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.39</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Contacted a business to complain about environmentally harmful products/policies</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.16</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.36</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Signed a petition supporting environmental protection</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.36</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Attended a meeting concerning the environment</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.17</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.37</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Public behaviors (0-7)</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c"></span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">1.80</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">1.92</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Avoided using products that harm the environment</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.66</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Tried to use less water in your household</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.75</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.43</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Bought a product because it was better for the environment</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.62</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Voluntarily recycled newspapers, glass, aluminum, motor oil, etc.</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.79</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.41</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Reduced your household's use of energy</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.78</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">0.42</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad66"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Private behaviors (0-5)</span></p></td><td class="cl-7c9dad67"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c"></span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">3.60</span></p></td><td class="cl-7c9dad6e"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">1.58</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7c9dad6f"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c">Total behaviors (0-12)</span></p></td><td class="cl-7c9dad70"><p class="cl-7c9d9478"><span class="cl-7c9c3a4c"></span></p></td><td class="cl-7c9dad71"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">5.40</span></p></td><td class="cl-7c9dad71"><p class="cl-7c9d9479"><span class="cl-7c9c3a4c">2.86</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-behaviors" class="quarto-xref">Table&nbsp;1</a>, the mean number of self-reported pro-environmental behaviors was 5.4, with a standard deviation of 2.86 in the 0 to 12 scale. For public behaviors the mean was 1.8, with a standard deviation of 1.92, and the mean number of self-reported private behaviors was 3.6, with a standard deviation of 1.58. Overall, respondents reported far more private than public behaviors. In terms of the behavior themselves, recycling had the highest mean at 0.79, which indicates that 79% of the respondents reported that they recycle, followed closely by reducing household energy use at 0.78. Buying a product because it was better for the environment had the lowest mean among private behaviors at 0.62. Among public behaviors, voting for or working for a candidate because of their environmental positions had the highest mean at 0.4, followed by signing a petition supporting environmental protection at 0.36. Contacting a business to complain about environmentally harmful products/policies had the lowest mean among public behaviors at 0.16.</p>
<p>Our independent variables are composite measures of cultural worldviews, ecological worldviews (New Ecological Paradigm), and the Connectedness to Nature Scale. For cultural cognition, we rely on the short form of the cultural cognition survey questions, which include three questions for each of the four cultural worldviews <span class="citation" data-cites="kahanCulturalCognitionConception2012">(see <a href="#ref-kahanCulturalCognitionConception2012" role="doc-biblioref">Kahan 2012</a>)</span>. Respondents were asked to indicate their agreement on a 1 (strongly disagree) to 4 (strongly agree) scale with three statements for each cultural worldview. To measure the New Ecological Paradigm (NEP) we used agreement with three statements on a 1 to 5 scale (1 - strongly disagree, 3 - neutral, 5 - strongly agree). Finally, for the Connectedness to Nature Scale (CNS), respondents were asked to indicate their agreement on a 1 to 5 scale (1 - strongly disagree, 3 - neutral, 5 - strongly agree) with three statements. For both the NEP and CNS, a higher value indicates a stronger orientation towards the environment.</p>
<p><a href="#tbl-measurement" class="quarto-xref">Table&nbsp;2</a> shows the question wording for each measurement item used for the latent constructs as well as the fit statistics for each of the constructs including Cronbach’s <span class="math inline">\(\alpha\)</span>, Composite Reliability (CR), and the Average Variance Extracted (AVE). As shown in <a href="#tbl-measurement" class="quarto-xref">Table&nbsp;2</a>, each construct showed sufficient reliability (α and CR &gt;0.70), except for the communitarianism scale. However, CR values between 0.60 and 0.70 are acceptable for exploratory analysis <span class="citation" data-cites="hairPrimerPartialLeast2015">(<a href="#ref-hairPrimerPartialLeast2015" role="doc-biblioref">Hair et al. 2015</a>)</span>.</p>
<div class="cell">
<div id="tbl-measurement" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-measurement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Measurement items and construct reliability (Cronbach’s α, composite reliability, average variance extracted)
</figcaption>
<div aria-describedby="tbl-measurement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-7cabc80e{}.cl-7ca8f84a{font-family:'Helvetica';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7ca8f84b{font-family:'Helvetica';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7caa2314{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7caa231e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7caa30b6{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30b7{width:3.85in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30c0{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30c1{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30ca{width:3.85in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30cb{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30cc{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30d4{width:3.85in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7caa30d5{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-7cabc80e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7caa30b6"><p class="cl-7caa2314"><span class="cl-7ca8f84a">Construct</span></p></th><th class="cl-7caa30b7"><p class="cl-7caa2314"><span class="cl-7ca8f84a">Statement</span></p></th><th class="cl-7caa30c0"><p class="cl-7caa231e"><span class="cl-7ca8f84a">α</span></p></th><th class="cl-7caa30c0"><p class="cl-7caa231e"><span class="cl-7ca8f84a">CR</span></p></th><th class="cl-7caa30c0"><p class="cl-7caa231e"><span class="cl-7ca8f84a">AVE</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Hierarchy</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">We have gone too far in pushing equal rights in this country.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.83</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.83</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">It seems like blacks, women, homosexuals and other groups don’t want equal rights, they want special rights just for them.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">The women’s rights movement has gone too far.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Egalitarianism</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">We need to dramatically reduce inequalities between the rich and poor, whites and people of color, and men and women.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.77</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.79</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.55</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Our society would be better off if the distribution of wealth was more equal.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">We live in a sexist society that is fundamentally set up to discriminate against women.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Individualism</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">If the government spent less time trying to fix everyone’s problems, we’d all be a lot better off.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.80</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.80</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.57</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Government regulations are almost always a waste of everyone’s time and money.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Our government tries to do too many things for too many people. We should just let people take care of themselves.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Communitarianism</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Sometimes government needs to make laws that keep people from hurting themselves.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.61</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.64</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.38</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Government should put limits on the choices individuals can make so they don’t get in the way of what’s good for society.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">The government should do more to advance society’s goals, even if that means limiting the freedom and choices of individuals.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">CNS</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">I think of the natural world as a community to which I belong.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.76</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.72</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">I often feel a kinship with animals and plants.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">I feel as though I belong to the Earth as equally as it belongs to me.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b">NEP</span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">Humans are severely abusing the environment.</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.70</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.73</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b">0.48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30c1"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30ca"><p class="cl-7caa2314"><span class="cl-7ca8f84b">The so-called “ecological crisis” facing humankind has been greatly exaggerated (reverse-coded).</span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30cb"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7caa30cc"><p class="cl-7caa2314"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30d4"><p class="cl-7caa2314"><span class="cl-7ca8f84b">If things continue on their present course, we will soon experience a major ecological catastrophe.</span></p></td><td class="cl-7caa30d5"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30d5"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td><td class="cl-7caa30d5"><p class="cl-7caa231e"><span class="cl-7ca8f84b"></span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>For the cultural worldview measures, we combined the scales to create dummy variables for hierarchical individualists and egalitarian communitarians. Respondents who scored at or above the median for both scales were coded as 1, and all others were coded as 0 <span class="citation" data-cites="kahanPolarizingImpactScience2012">(similar to <a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>)</span>. Overall, 213 respondents (42.5%) were classified as hierarchical individualists and 176 respondents (35.1%) as egalitarian communitarians.</p>
<p>To test our hypothesis, we estimated a Structural Equation Model (SEM) using the <code>lavaan</code> package in <code>R</code> <span class="citation" data-cites="rosseelLavaanPackageStructural2012">(<a href="#ref-rosseelLavaanPackageStructural2012" role="doc-biblioref">Rosseel 2012</a>)</span>. The dependent variable, self-reported pro-environmental behaviors, is an observed variable, and the cultural cognition worldviews, the CNS, and the NEP scale are latent constructs using the measures in <a href="#tbl-measurement" class="quarto-xref">Table&nbsp;2</a>. In addition, we examine the mediation effects of environmental orientation by examining the direct, indirect, and total effects of cultural worldviews on pro-environmental behavior.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>The SEM results are shown in <a href="#fig-structural" class="quarto-xref">Figure&nbsp;2</a>. For clarity, we only include the structural model and only the paths that were statistically significant at p&lt;0.05.</p>
<div id="fig-structural" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-structural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Structural model of cultural worldviews, ecological worldviews, connectedness to nature, and pro-environmental behaviors.
</figcaption>
<div aria-describedby="fig-structural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cc-behave_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<p>As shown in <a href="#fig-structural" class="quarto-xref">Figure&nbsp;2</a>, as expected, hierarchical individualists were negatively associated with ecological worldviews (NEP). This was expected because a positive value indicates a more environmentally centric worldview. Also as expected, egalitarian-communitarians were positively associated with the NEP. Additionally, the cognitive element of environmental orientations, the NEP, was positively associated with the affective element, the CNS, as expected. Regarding pro-environmental behaviors, as expected, both elements of environmental orientation were positively associated with an increase in the number of behaviors; however, there was no direct relationship between cultural worldviews and behavior. Finally, egalitarian-communitarians were more likely to feel connected to nature; therefore, they had the strongest environmental orientation, as both the cognitive and affective elements were significant.</p>
<p>The path coefficients are standardized, which means that they equal the expected change in the standard deviation (sd) of the outcome variables for each standard deviation of the predictor, keeping all other variables constant. For example, the path coefficient from CNS to behaviors is 0.404; therefore, holding the other variables constant, a 1-sd increase in the CNS scale is associated with a 0.404-sd increase in the number of behaviors. In terms of the number of actual predicted behaviors, as shown in <a href="#tbl-behaviors" class="quarto-xref">Table&nbsp;1</a>, the sd of behaviors is 2.86, and 0.404 × 2.86 equals 1.155 predicted additional behaviors for each 1-sd increase in the CNS.</p>
<p>Standardized path coefficients allow for a comparison of the strengths of the various relationships. As shown, the strongest relationship is between the two environmental orientation measures, with the NEP to CNS path = 0.425. In terms of the relationship to behaviors, the CNS path was the strongest at 0.404, followed by the NEP to behavior path at 0.240. No other paths to behaviors were significant. For cultural worldviews to environmental orientations, hierarchal individualists have the strongest (negative) relationship, at -0.392, with ecological worldviews. Egalitarian communitarians has a stronger relationship with ecological worldviews (0.231) than with connectedness to nature (0.188), but is significantly associated with both.</p>
<p>The fit statistics for the model are shown in <a href="#tbl-fit-full" class="quarto-xref">Table&nbsp;3</a> and include the Root Mean Square Error of Approximation (RMSEA), Comparative Fit Index (CFI), Tucker-Lewis Index (TFI), Root Mean Square Error of Approximation (RMSEA) and its confidence intervals, Standardized Root Mean Square Residual (SRMR), and AIC and BIC. Overall, the statistics indicate a reasonable fit for the model <span class="citation" data-cites="huCutoffCriteriaFit1999">(<a href="#ref-huCutoffCriteriaFit1999" role="doc-biblioref">Hu and Bentler 1999</a>)</span>.</p>
<div class="cell">
<div id="tbl-fit-full" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fit-full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Model fit statistics for the structural model
</figcaption>
<div aria-describedby="tbl-fit-full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-7ccc9ce6{}.cl-7cca1c0a{font-family:'Helvetica';font-size:8pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7cca1c0b{font-family:'Helvetica';font-size:8pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7cca1c14{font-family:'Helvetica';font-size:7pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7ccb2866{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:2pt;padding-right:2pt;line-height: 1;background-color:transparent;}.cl-7ccb2867{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:2pt;padding-right:2pt;line-height: 1;background-color:transparent;}.cl-7ccb2870{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7ccb3482{width:1.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb3483{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb348c{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb348d{width:0.45in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb3496{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb3497{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb3498{width:1.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34a0{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34a1{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34aa{width:0.45in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34ab{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34ac{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34b4{width:1.55in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34b5{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34b6{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34b7{width:0.45in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34be{width:0.8in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7ccb34bf{width:0.55in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-7ccc9ce6"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7ccb3482"><p class="cl-7ccb2866"><span class="cl-7cca1c0a">Model</span></p></th><th class="cl-7ccb3483"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">Chi-sq</span></p></th><th class="cl-7ccb348c"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">df</span></p></th><th class="cl-7ccb348d"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">CFI</span></p></th><th class="cl-7ccb348d"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">TLI</span></p></th><th class="cl-7ccb3483"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">RMSEA</span></p></th><th class="cl-7ccb3496"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">RMSEA 90% CI</span></p></th><th class="cl-7ccb348d"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">SRMR</span></p></th><th class="cl-7ccb3497"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">AIC</span></p></th><th class="cl-7ccb3497"><p class="cl-7ccb2867"><span class="cl-7cca1c0a">BIC</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7ccb3498"><p class="cl-7ccb2866"><span class="cl-7cca1c0b">Full (HI/EC, + direct paths)</span></p></td><td class="cl-7ccb34a0"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">141.46</span></p></td><td class="cl-7ccb34a1"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">40</span></p></td><td class="cl-7ccb34aa"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">0.905</span></p></td><td class="cl-7ccb34aa"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">0.834</span></p></td><td class="cl-7ccb34a0"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">0.071</span></p></td><td class="cl-7ccb34ab"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">(0.059, 0.084)</span></p></td><td class="cl-7ccb34aa"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">0.039</span></p></td><td class="cl-7ccb34ac"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">10,559.8</span></p></td><td class="cl-7ccb34ac"><p class="cl-7ccb2867"><span class="cl-7cca1c0b">10,715.9</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="10" class="cl-7ccb34b4"><p class="cl-7ccb2870"><span class="cl-7cca1c14">Note: Model controls for age, gender, race, education, and household income. Conventional benchmarks: CFI/TLI ≥ 0.90 acceptable, ≥ 0.95 good; RMSEA ≤ 0.08 acceptable, ≤ 0.05 good; SRMR ≤ 0.08 good (Hu and Bentler 1999).</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>Next, we examined the direct, indirect, and total effects of cultural worldviews on behavior. Those results are shown in <a href="#tbl-serial-effects" class="quarto-xref">Table&nbsp;4</a>.</p>
<div class="cell">
<div id="tbl-serial-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-serial-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Standardized decomposition of cultural worldview group effects on pro-environmental behavior.
</figcaption>
<div aria-describedby="tbl-serial-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-7cd4c31c{}.cl-7cd1cd2e{font-family:'Helvetica';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7cd1cd38{font-family:'Helvetica';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7cd1cd39{font-family:'Helvetica';font-size:8pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7cd31d0a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7cd31d14{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7cd31d15{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7cd32db8{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32db9{width:0.7in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dba{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dc2{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dc3{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dc4{width:0.7in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dc5{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dcc{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dcd{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dd6{width:0.7in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dd7{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32dd8{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32de0{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32de1{width:0.7in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32de2{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7cd32de3{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-7cd4c31c"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7cd32db8"><p class="cl-7cd31d0a"><span class="cl-7cd1cd2e">Predictor</span></p></th><th class="cl-7cd32db9"><p class="cl-7cd31d14"><span class="cl-7cd1cd2e">Direct</span></p></th><th class="cl-7cd32dba"><p class="cl-7cd31d14"><span class="cl-7cd1cd2e">Serial (NEP-CNS)</span></p></th><th class="cl-7cd32dc2"><p class="cl-7cd31d14"><span class="cl-7cd1cd2e">Total indirect</span></p></th><th class="cl-7cd32db9"><p class="cl-7cd31d14"><span class="cl-7cd1cd2e">Total</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7cd32dc3"><p class="cl-7cd31d0a"><span class="cl-7cd1cd38">Hierarch-Individualist</span></p></td><td class="cl-7cd32dc4"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">0.036</span></p></td><td class="cl-7cd32dc5"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">-0.067***</span></p></td><td class="cl-7cd32dcc"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">-0.157***</span></p></td><td class="cl-7cd32dc4"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">-0.121**</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7cd32dcd"><p class="cl-7cd31d0a"><span class="cl-7cd1cd38">Egalitarian-Communitarian</span></p></td><td class="cl-7cd32dd6"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">0.028</span></p></td><td class="cl-7cd32dd7"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">0.040***</span></p></td><td class="cl-7cd32dd8"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">0.171***</span></p></td><td class="cl-7cd32dd6"><p class="cl-7cd31d14"><span class="cl-7cd1cd38">0.199***</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="5" class="cl-7cd32de0"><p class="cl-7cd31d15"><span class="cl-7cd1cd39">Note: Effects are from the full combined model, controlling for age, gender, race, education, and household income. † p&lt;0.10, * p&lt;0.05, ** p&lt;0.01, *** p&lt;0.001.</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>For hierarchical individualists, the total effect on behaviors was -0.121, and for egalitarian communitarians, it was 0.199. However, as shown in <a href="#fig-structural" class="quarto-xref">Figure&nbsp;2</a> and <a href="#tbl-serial-effects" class="quarto-xref">Table&nbsp;4</a>, there is no direct relationship between cultural worldviews and behaviors; therefore, the effects are strictly a result of indirect effects, as environmental orientations appear to mediate the relationship between cultural worldviews and behaviors.</p>
<p>The serial effect includes the paths of cultural worldviews to the NEP, NEP to CNS, and CNS to behaviors. For example, for hierarchical individualists, the serial effect is calculated as −0.392 × 0.425 × 0.404 = −0.067. The total indirect effect captures the paths from cultural worldviews to NEP, NEP to behavior, cultural worldviews to CNS, and the serial effect. For hierarchical individualists that is (−0.392×0.240) + (0.010×0.404) + (−0.067) = −0.094 + 0.004 − 0.067 = −0.157. Finally, the total effect is simply the direct effect plus the total indirect effect.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Scholars have noted a gap between values and beliefs about the environment and pro-environmental behavior. In particular, cultural worldviews derived from cultural cognition, specifically egalitarianism and communitarianism, have been shown to inform views on several environmental issues as well as overall attitudes toward the environment. However, little research has found a connection between cultural worldviews and environmental behavior <span class="citation" data-cites="markleUnderstandingProEnvironmentalBehavior2019">(but see <a href="#ref-markleUnderstandingProEnvironmentalBehavior2019" role="doc-biblioref">Markle 2019</a>)</span>. In this paper, we developed and tested a conceptual model based on the existing VBN and ACF frameworks, in which cultural worldviews influence environmental orientations, and environmental orientations influence behaviors. Additionally, our contribution notes that cultural and ecological worldviews are cognitive features of belief systems that provide both a basis of values and beliefs as well as a series of psychological mechanisms that ensure that beliefs and attitudes are consistent with the underlying worldviews. In turn, these cognitive features of belief systems influence the affective element of environmental orientations, which is the emotional connection to nature. Finally, the affective element of environmental orientation is most strongly associated with pro-environmental behavior.</p>
<p>Based on our conceptual model, we posited that egalitarian communitarians would be positively associated with environmental orientations and environmental behavior, and hierarchical individualists would be negatively associated with environmental orientations and environmental behavior. Additionally, we expected that the cognitive element of environmental orientation would be associated with the affective element and that both elements of environmental orientation would be associated with increased self-reported pro-environmental behaviors. Overall, we found mixed results for our hypotheses. As expected, egalitarian communitarians were associated with both the CNS and NEP; however, they were not directly associated with behavior. In addition, hierarchical individualists were less likely to have an ecological worldview, but they were no more or less likely to feel connected to nature than those with other cultural worldviews. Finally, both elements of environmental orientation were associated with more pro-environmental behaviors, and based on the standardized coefficients, the affective element (CNS) had a stronger relationship than the cognitive element (NEP).</p>
<p>Given the uncertainty about the relationship between cultural worldviews and pro-environmental behaviors, we also conducted a mediation analysis to examine whether environmental orientations mediate the relationship between cultural worldviews and behaviors. If so, cultural worldviews would still influence behavior but only indirectly. We found that both the cognitive and affective elements of environmental orientations mediated the relationship between cultural worldviews and environmental behaviors. This means that the effect of cultural worldviews on pro-environmental behaviors is based solely on their influence on environmental orientations. Along with the results of the structural equation modeling, this helps us understand cultural cognition as an antecedent of environmental orientation and fill some of the attitude-behavior gap.</p>
<p>We also found that the Connectedness to Nature Scale (CNS) had more predictive power regarding environmental behaviors than the NEP, based on the standardized path coefficients shown in <a href="#fig-structural" class="quarto-xref">Figure&nbsp;2</a>. This finding is in line with work showing that the CNS is a stronger predictor than the NEP <span class="citation" data-cites="sparksMeasuringEnvironmentalValues2021">(e.g., <a href="#ref-sparksMeasuringEnvironmentalValues2021" role="doc-biblioref">Sparks et al. 2021</a>)</span>. Additionally, the CNS and NEP measure two distinct concepts that can be grouped under the umbrella of environmental orientation, where the NEP is explicitly a measure of environmental attitude, while the CNS is a measure of emotional connection to nature. Overall, the affective element of environmental orientations is more proximate to behaviors than the cognitive element. Similarly, a recent study found that harnessing the right mix of emotions is a powerful motivator of climate action <span class="citation" data-cites="kovacsActingWeFeel2024">(<a href="#ref-kovacsActingWeFeel2024" role="doc-biblioref">Kovács et al. 2024</a>)</span>.</p>
<p>Another reason that the affective element of environmental orientation, the CNS, displays more power than the cognitive NEP to influence behavior is that there has been a slow decline in environmental concern as measured by the NEP <span class="citation" data-cites="louMetaanalysisTemporalShifts2022">(<a href="#ref-louMetaanalysisTemporalShifts2022" role="doc-biblioref">Lou et al. 2022</a>)</span>. The downtrend of the NEP was shown through meta-analysis; however, there was no indication of why this may be happening. We are not aware of a similar study tracking CNS over time, but that may prove to be a fruitful avenue for further study. If only the NEP is declining over time, that may indicate that the measurement instrument is becoming outdated, potentially because of shifts over time making the distinction between the dominant social paradigm and the new ecological paradigm less apt. For example, many see technological innovation as the key to unlocking a new green economy rather than destroying the earth. Relatedly, perhaps the language used in the NEP has just become outmoded and out of line with how environmentalists currently would express environmental attitude <span class="citation" data-cites="sparksMeasuringProenvironmentalOrientation2022">(see <a href="#ref-sparksMeasuringProenvironmentalOrientation2022" role="doc-biblioref">Sparks, Ehret, and Brick 2022</a> for a discussion of this)</span>.</p>
<p>There are a few limitations with this paper. First, the sample size was relatively small (n = 501). While we have no reason to think that a larger sample size would substantively change the results, the results should be replicated with more respondents. Additionally, our data are cross-sectional, and future research should measure the nature of the relationships between cultural cognition, environmental orientation, and environmental behavior over time using panel data. Panel data could explore the strength and consistency of the relationships over time. Finally, causality is difficult to determine using SEM with cross-sectional data. While we argue that there are theoretical and empirical reasons to see cognition preceding the affective elements of belief systems, we recognize that the statistical associations we found do not constitute definitive evidence of causality. Therefore, we have been careful in our language when describing our findings.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<!-- cognitive precedes affective because of the empirical proximity to behaviors; sequence based on previous research -->
<p>Achieving environmentally sustainable outcomes requires significant engagement in pro-environmental behavior across all segments of society. While a large body of research exists that examines pro-environmental behaviors, some gaps remain. In this paper, we developed a conceptual model that draws a distinction between the cognitive and affective elements of belief systems and tested hypotheses based on that approach. We argue that combining cultural cognition and environmental orientation should improve our understanding of the drivers of environmentally protective behaviors</p>
<p>Because cultural cognition shapes how an individual responds to risk <span class="citation" data-cites="kahanPolarizingImpactScience2012">(e.g., <a href="#ref-kahanPolarizingImpactScience2012" role="doc-biblioref">Kahan et al. 2012</a>)</span>, it was something of a puzzle as to why it only weakly correlates to behavior that protects the environment – an action that can be seen as a way to reduce environmental risk to the individual. The evidence presented in this study suggests that environmental orientation, whether attitude (NEP) or emotional connection (CNS), is an important link in this relationship. Additionally, we presented evidence that cultural worldviews are best thought of as indirect predictors of pro-environmental behavior. This relationship was mediated by environmental orientation, as measured by both the NEP and CNS. Furthermore, by explaining behavior with a mediation model, we could close some of the so-called attitude-behavior gap. When cultural cognition and environmental orientation are aligned, people are more likely to engage in environmentally protective behaviors.</p>
<p>Another implication of this study is further evidence that CNS is a stronger predictor of behavior than NEP. This may be useful for researchers trying to decide which measures of pro-environmental orientation to include in their questionnaires. We would like to see further testing of this finding in studies in other contexts and through meta-analytic techniques.</p>
<!-- Altogether, . 

Specifically, in this paper, we suggest that environmental orientation mediates the relationship between cultural cognition and environmental behavior. Essentially, environmental orientation helps connect cultural worldviews and risk perceptions to action to reduce that risk. Moreover, cultural cognition helps to bridge the attitude-behavior gap by providing a basis through environmental orientations derive and subsequently influence behavior.



In addition, environmental orientation is likely associated with the myths of nature connected to the various cultural worldviews. As a result, environmental orientation, as measured by NEP and/or CNS, likely mediates the relationship between cultural cognition and environmental behavior. Figure 1 


To further elaborate the attitude-behavior model we examine the relationship between cultural cognition, environmental orientation (attitude and emotional connection), and behavior.


In this paper, we examine whether environmental orientations mediate the relationship between cultural cognition and behavior such that cultural cognition shapes environmental orientations, which in turn influences pro-environmental behavior. In doing so, we argue that when cultural cognition aligns with environmental orientation, there is a stronger relationship with pro-environmental behaviors than when considering attitude or affect alone, thus reducing the attitude-behavior gap.

-->
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ballewSystemsThinkingPathway2019" class="csl-entry" role="listitem">
Ballew, Matthew T., Matthew H. Goldberg, Seth A. Rosenthal, Abel Gustafson, and Anthony Leiserowitz. 2019. <span>“Systems <span>Thinking</span> as a <span>Pathway</span> to <span>Global Warming Beliefs</span> and <span>Attitudes Through</span> an <span>Ecological Worldview</span>.”</span> <em>Proceedings of the National Academy of Sciences</em>.
</div>
<div id="ref-boudetFrackingControversyCommunication2014" class="csl-entry" role="listitem">
Boudet, Hilary, Christopher Clarke, Dylan Bugden, Edward Maibach, Connie Roser-Renouf, and Anthony Leiserowitz. 2014. <span>“<span>‘<span>Fracking</span>’</span> <span>Controversy</span> and <span>Communication</span>: <span>Using National Survey Data</span> to <span>Understand Public Perceptions</span> of <span>Hydraulic Fracturing</span>.”</span> <em>Energy Policy</em> 65: 57–67.
</div>
<div id="ref-brickUnearthingGreenPersonality2016" class="csl-entry" role="listitem">
Brick, Cameron, and Gary J. Lewis. 2016. <span>“Unearthing the <span>‘<span>Green</span>’</span> <span>Personality</span>: <span>Core Traits Predict Environmentally Friendly Behavior</span>.”</span> <em>Environment and Behavior</em> 48(5): 635–58.
</div>
<div id="ref-canlasMoreTwentyYears2022" class="csl-entry" role="listitem">
Canlas, Ian Phil, Mageswary Karpudewan, and Nur Sabrina Mohamed Ali Khan. 2022. <span>“More <span>Than Twenty Years</span> of <span>Value-Belief-Norm Theory</span> of <span>Environmentalism</span>: <span>What Has Been</span> and <span>Yet To Be Done</span>?”</span> <em>Interdisciplinary Journal of Environmental and Science Education</em> 18(2): e2269.
</div>
<div id="ref-chenExaminationValuebeliefnormTheory2015" class="csl-entry" role="listitem">
Chen, Mei-Fang. 2015. <span>“An <span>Examination</span> of the <span>Value-Belief-Norm Theory Model</span> in <span>Predicting Pro-Environmental Behaviour</span> in <span>Taiwan</span>.”</span> <em>Asian Journal of Social Psychology</em> 18(2): 145–51.
</div>
<div id="ref-derdowskiNewEcologicalParadigm2020" class="csl-entry" role="listitem">
Derdowski, Lukasz Andrzej, Åsa Helen Grahn, Håvard Hansen, and Heidi Skeiseid. 2020. <span>“The <span>New Ecological Paradigm</span>, <span>Pro-Environmental Behaviour</span>, and the <span>Moderating Effects</span> of <span>Locus</span> of <span>Control</span> and <span>Self-Construal</span>.”</span> <em>Sustainability</em> 12(18): 7728.
</div>
<div id="ref-dietzEnvironmentalValues2005" class="csl-entry" role="listitem">
Dietz, Thomas, Amy Fitzgerald, and Rachael Shwom. 2005. <span>“Environmental <span>Values</span>.”</span> <em>Annual Review of Environment and Resources</em> 30(1): 335–72.
</div>
<div id="ref-douglasRiskCultureEssay1982" class="csl-entry" role="listitem">
Douglas, Mary, and Aaron Wildavsky. 1982. <em>Risk and <span>Culture</span>: <span>An Essay</span> on the <span>Selection</span> of <span>Technological</span> and <span>Environmental Dangers</span></em>. Berkeley, CA: University of California Press.
</div>
<div id="ref-dunlapNewEnvironmentalParadigm1978" class="csl-entry" role="listitem">
Dunlap, Riley E., and Kent D. Van Liere. 1978. <span>“The <span>‘<span>New Environmental Paradigm</span>’</span>.”</span> <em>The Journal of Environmental Education</em> 9(4): 10–19.
</div>
<div id="ref-dunlapNewTrendsMeasuring2000" class="csl-entry" role="listitem">
Dunlap, Riley E., Kent D. Van Liere, Angela G. Mertig, and Robert Emmet Jones. 2000. <span>“New <span>Trends</span> in <span>Measuring Environmental Attitudes</span>: <span>Measuring Endorsement</span> of the <span>New Ecological Paradigm</span>: <span>A Revised NEP Scale</span>.”</span> <em>Journal of Social Issues</em> 56(3): 425–42.
</div>
<div id="ref-fornaraExtendedValueBeliefNormTheory2020" class="csl-entry" role="listitem">
Fornara, Ferdinando, Erica Molinario, Massimiliano Scopelliti, Mirilia Bonnes, Flavia Bonaiuto, Lavinia Cicero, Jeroen Admiraal, Almut Beringer, Tom Dedeurwaerdere, Wouter De Groot, Juha Hiedanpää, Paul Knights, Luuk Knippenberg, Chris Ovenden, Katarina Polajnar Horvat, Florin Popa, Carmen Porras-Gomez, Aleš Smrekar, Nathalie Soethe, Jose Luis Vivero-Pol, Riyan Van Den Born, and Marino Bonaiuto. 2020. <span>“The <span>Extended Value-Belief-Norm Theory Predicts Committed Action</span> for <span>Nature</span> and <span>Biodiversity</span> in <span>Europe</span>.”</span> <em>Environmental Impact Assessment Review</em> 81: 106338.
</div>
<div id="ref-giffordPersonalSocialFactors2014" class="csl-entry" role="listitem">
Gifford, Robert, and Andreas Nilsson. 2014. <span>“Personal and <span>Social Factors That Influence Pro-Environmental Concern</span> and <span>Behaviour</span>: <span>A Review</span>.”</span> <em>International Journal of Psychology</em>: n/a–.
</div>
<div id="ref-gkargkavouziMultidimensionalMeasureEnvironmental2019" class="csl-entry" role="listitem">
Gkargkavouzi, Anastasia, George Halkos, and Steriani Matsiori. 2019. <span>“A <span class="nocase">Multi-dimensional Measure</span> of <span>Environmental Behavior</span>: <span>Exploring</span> the <span>Predictive Power</span> of <span>Connectedness</span> to <span>Nature</span>, <span>Ecological Worldview</span> and <span>Environmental Concern</span>.”</span> <em>Social Indicators Research</em> 143(2): 859–79.
</div>
<div id="ref-grendstadNewEcologicalParadigm1999" class="csl-entry" role="listitem">
Grendstad, Gunnar. 1999. <span>“The <span>New Ecological Paradigm Scale</span>: <span>Examination</span> and <span>Scale Analysis</span>.”</span> <em>Environmental Politics</em> 8(4): 194–205.
</div>
<div id="ref-hairPrimerPartialLeast2015" class="csl-entry" role="listitem">
Hair, Joseph Franklin, G. Tomas M. Hult, Christian M. Ringle, and Marko Sarstedt. 2015. 38 <em>A <span>Primer</span> on <span>Partial Least Squares Structural Equation Modeling</span> (<span>PLS-SEM</span>)</em>. Los Angeles, CA: SAGE Publications.
</div>
<div id="ref-henryUnderstandingEnvironmentalCognition2012" class="csl-entry" role="listitem">
Henry, Adam Douglas, and Thomas Dietz. 2012. <span>“Understanding <span>Environmental Cognition</span>.”</span> <em>Organization &amp; Environment</em> 25(3): 238–58.
</div>
<div id="ref-huCutoffCriteriaFit1999" class="csl-entry" role="listitem">
Hu, Li‐tze, and Peter M. Bentler. 1999. <span>“Cutoff <span>Criteria</span> for <span>Fit Indexes</span> in <span>Covariance Structure Analysis</span>: <span>Conventional Criteria Versus New Alternatives</span>.”</span> <em>Structural Equation Modeling: A Multidisciplinary Journal</em> 6(1): 1–55.
</div>
<div id="ref-jenkins-smithBeliefSystemContinuity2014" class="csl-entry" role="listitem">
Jenkins-Smith, Hank C., Carol L. Silva, Kuhika Gupta, and Joseph T. Ripberger. 2014. <span>“Belief <span>System Continuity</span> and <span>Change</span> in <span>Policy Advocacy Coalitions</span>: <span>Using Cultural Theory</span> to <span>Specify Belief Systems</span>, <span>Coalitions</span>, and <span>Sources</span> of <span>Change</span>.”</span> <em>Policy Studies Journal</em> 42(4): 484–508.
</div>
<div id="ref-jenkins-smithIdeologyCultureRisk1994" class="csl-entry" role="listitem">
Jenkins-Smith, Hank C., and Walter K. Smith. 1994. <span>“Ideology, <span>Culture</span>, and <span>Risk Perception</span>.”</span> In <em>Politics, <span>Policy</span>, and <span>Culture</span></em>, Political <span>Culture Series</span>, eds. Dennis J. Coyle and Richard J. Ellis. Boulder, CO: Westview Press, 17–32.
</div>
<div id="ref-jonesLeadingWayCompromise2011" class="csl-entry" role="listitem">
Jones, Michael D. 2011. <span>“Leading the <span>Way</span> to <span>Compromise</span>? <span>Cultural Theory</span> and <span>Climate Change Opinion</span>.”</span> <em>PS: Political Science &amp; Politics</em> 44(04): 720–25.
</div>
<div id="ref-kahanCulturalCognitionConception2012" class="csl-entry" role="listitem">
Kahan, Dan M. 2012. <span>“Cultural <span>Cognition</span> as a <span>Conception</span> of the <span>Cultural Theory</span> of <span>Risk</span>.”</span> In <em>Handbook of <span>Risk Theory</span>: <span>Epistemology</span>, <span>Decision Theory</span>, <span>Ethics</span>, and <span>Social Implications</span> of <span>Risk</span></em>, eds. Sabine Roeser, Rafaela Hillerbrand, Per Sandin, and Martin Peterson. Springer, 725–59.
</div>
<div id="ref-kahanCulturalCognitionPublic2006" class="csl-entry" role="listitem">
Kahan, Dan M., and Donald Braman. 2006. <span>“Cultural <span>Cognition</span> and <span>Public Policy</span>.”</span> <em>Yale Law and Policy Review</em> 24(1): 147–70.
</div>
<div id="ref-kahanCultureIdentityProtectiveCognition2007" class="csl-entry" role="listitem">
Kahan, Dan M., Donald Braman, John Gastil, Paul Slovic, and C. K. Mertz. 2007. <span>“Culture and <span>Identity-Protective Cognition</span>: <span>Explaining</span> the <span>White-Male Effect</span> in <span>Risk Perception</span>.”</span> <em>Journal of Empirical Legal Studies</em> 4(3): 465–505.
</div>
<div id="ref-kahanGeoengineeringClimateChange2015" class="csl-entry" role="listitem">
Kahan, Dan M., Hank Jenkins-Smith, Tor Tarantola, Carol L. Silva, and Donald Braman. 2015. <span>“Geoengineering and <span>Climate Change Polarization Testing</span> a <span>Two-Channel Model</span> of <span>Science Communication</span>.”</span> <em>The ANNALS of the American Academy of Political and Social Science</em> 658(1): 192–222.
</div>
<div id="ref-kahanPolarizingImpactScience2012" class="csl-entry" role="listitem">
Kahan, Dan M., Ellen Peters, Maggie Wittlin, Paul Slovic, Lisa Larrimore Ouellette, Donald Braman, and Gregory Mandel. 2012. <span>“The <span>Polarizing Impact</span> of <span>Science Literacy</span> and <span>Numeracy</span> on <span>Perceived Climate Change Risks</span>.”</span> <em>Nature Climate Change</em> 2(10): 732–35.
</div>
<div id="ref-kaiserOffsettingBehavioralCosts2021" class="csl-entry" role="listitem">
Kaiser, Florian G., Alexandra Kibbe, and Liane Hentschke. 2021. <span>“Offsetting <span>Behavioral Costs</span> with <span>Personal Attitudes</span>: <span>A Slightly More Complex View</span> of the <span>Attitude-Behavior Relation</span>.”</span> <em>Personality and Individual Differences</em> 183: 111158.
</div>
<div id="ref-kollmussMindGapWhy2002" class="csl-entry" role="listitem">
Kollmuss, Anja, and Julian Agyeman. 2002. <span>“Mind the <span>Gap</span>: <span>Why Do People Act Environmentally</span> and <span>What Are</span> the <span>Barriers</span> to <span>Pro-Environmental Behavior</span>?”</span> <em>Environmental Education Research</em> 8(3): 239–60.
</div>
<div id="ref-kovacsActingWeFeel2024" class="csl-entry" role="listitem">
Kovács, Lilla Nóra, Gesine Jordan, Frida Berglund, Benedict Holden, Elena Niehoff, Felicia Pohl, Mariem Younssi, Inés Zevallos, Csilla Ágoston, Attila Varga, and Gyöngyi Kökönyei. 2024. <span>“Acting as <span>We Feel</span>: <span>Which Emotional Responses</span> to the <span>Climate Crisis Motivate Climate Action</span>.”</span> <em>Journal of Environmental Psychology</em> 96: 102327.
</div>
<div id="ref-liobikieneImportanceEnvironmentalKnowledge2019" class="csl-entry" role="listitem">
Liobikienė, Genovaitė, and Mykolas Simas Poškus. 2019. <span>“The <span>Importance</span> of <span>Environmental Knowledge</span> for <span>Private</span> and <span>Public Sphere Pro-Environmental Behavior</span>: <span>Modifying</span> the <span>Value-Belief-Norm Theory</span>.”</span> <em>Sustainability</em> 11(12): 3324.
</div>
<div id="ref-louMetaanalysisTemporalShifts2022" class="csl-entry" role="listitem">
Lou, Xiaobin, Liman Man Wai Li, Weiwei Xia, and Qishan Zhu. 2022. <span>“A <span>Meta-Analysis</span> of <span>Temporal Shifts</span> in <span>Environmental Concern Between</span> 1994 and 2017: <span>An Examination</span> of the <span>New Environmental Paradigm</span>.”</span> <em>Anthropocene</em> 38: 100335.
</div>
<div id="ref-mackayPeopleWhoFeel2019" class="csl-entry" role="listitem">
Mackay, Caroline M. L., and Michael T. Schmitt. 2019. <span>“Do <span>People Who Feel Connected</span> to <span>Nature Do More</span> to <span>Protect It</span>? <span>A Meta-Analysis</span>.”</span> <em>Journal of Environmental Psychology</em> 65: 101323.
</div>
<div id="ref-markleUnderstandingProEnvironmentalBehavior2019" class="csl-entry" role="listitem">
Markle, Gail. 2019. <span>“Understanding <span>Pro-Environmental Behavior</span> in the <span>US</span>: <span>Insights</span> from <span>Grid-Group Cultural Theory</span> and <span>Cognitive Sociology</span>.”</span> <em>Sustainability</em> 11(2): 532.
</div>
<div id="ref-mayerConnectednessNatureScale2004" class="csl-entry" role="listitem">
Mayer, F. Stephan, and Cynthia McPherson Frantz. 2004. <span>“The <span>Connectedness</span> to <span>Nature Scale</span>: <span>A Measure</span> of <span>Individuals</span>’ <span>Feeling</span> in <span>Community</span> with <span>Nature</span>.”</span> <em>Journal of Environmental Psychology</em> 24(4): 503–15.
</div>
<div id="ref-moyerCulturalPredispositionsSpecific2019" class="csl-entry" role="listitem">
Moyer, Rachael M., and Geoboo Song. 2019. <span>“Cultural <span>Predispositions</span>, <span>Specific Affective Feelings</span>, and <span>Benefit</span>–<span>Risk Perceptions</span>: <span>Explicating Local Policy Elites</span>’ <span>Perceived Utility</span> of <span>High Voltage Power Line Installations</span>.”</span> <em>Journal of Risk Research</em> 22(4): 416–31.
</div>
<div id="ref-nisbetNatureRelatednessScale2009" class="csl-entry" role="listitem">
Nisbet, Elizabeth K., John M. Zelenski, and Steven A. Murphy. 2009. <span>“The <span>Nature Relatedness Scale</span>: <span>Linking Individuals</span>’ <span>Connection With Nature</span> to <span>Environmental Concern</span> and <span>Behavior</span>.”</span> <em>Environment and Behavior</em> 41(5): 715–40.
</div>
<div id="ref-nohrstedtAdvocacyCoalitionFramework2023" class="csl-entry" role="listitem">
Nohrstedt, Daniel, Karin Ingold, Christopher M. Weible, Elizabeth A. Koebele, Kristin L. Olofsson, Keiichi Satoh, and Hank C. Jenkins-Smith. 2023. <span>“The <span>Advocacy Coalition Framework</span>: <span>Progress</span> and <span>Emerging Areas</span>.”</span> In <em>Theories <span>Of The Policy Process</span></em>, ed. Christopher M. Weible. New York, NY: Routledge, 130–60.
</div>
<div id="ref-nowlinEnvironmentalPolicymakingEra2019" class="csl-entry" role="listitem">
Nowlin, Matthew C. 2019. <em>Environmental <span>Policymaking</span> in an <span>Era</span> of <span>Climate Change</span></em>. New York, NY: Routledge.
</div>
<div id="ref-nowlinWhoShouldMore2022" class="csl-entry" role="listitem">
———. 2022. <span>“Who <span>Should</span> <span>‘<span>Do More</span>’</span> <span>About Climate Change</span>? <span>Cultural Theory</span>, <span>Polycentricity</span>, and <span>Public Support</span> for <span>Climate Change Actions Across Actors</span> and <span>Governments</span>.”</span> <em>Review of Policy Research</em> 39(4): 468–85.
</div>
<div id="ref-nowlinCulturalTheoryPartisanship2020" class="csl-entry" role="listitem">
Nowlin, Matthew C., and Thomas M. Rabovsky. 2020. <span>“A <span>Cultural Theory</span> of <span>Partisanship</span> and <span>Policy Attitudes</span>.”</span> <em>Social Science Quarterly</em> 101(2): 878–92.
</div>
<div id="ref-overdevestUsingCulturalCognition2013" class="csl-entry" role="listitem">
Overdevest, Christine, and Lisa Christiansen. 2013. <span>“Using <span>‘<span>Cultural Cognition</span>’</span> to <span>Predict Environmental Risk Perceptions</span> in a <span>Florida Water-Supply Planning Process</span>.”</span> <em>Society &amp; Natural Resources</em> 26(9): 987–1007.
</div>
<div id="ref-quanCognitionConservationApplying2025" class="csl-entry" role="listitem">
Quan, Xuefeng, Xiaoyu Song, and Thi Phuong Nguyen. 2025. <span>“From <span>Cognition</span> to <span>Conservation</span>: <span>Applying Grid</span>–<span>Group Cultural Theory</span> to <span>Manage Natural Resources</span>.”</span> <em>Sustainability</em> 17(10): 4613.
</div>
<div id="ref-riepeValuesBeliefsNorms2021" class="csl-entry" role="listitem">
Riepe, Carsten, Ulf Liebe, Marie Fujitani, Sophia Kochalski, Øystein Aas, and Robert Arlinghaus. 2021. <span>“Values, <span>Beliefs</span>, <span>Norms</span>, and <span>Conservation-Oriented Behaviors</span> Toward <span>Native Fish Biodiversity</span> in <span>Rivers</span>: <span>Evidence</span> from <span>Four European Countries</span>.”</span> <em>Society &amp; Natural Resources</em> 34(6): 703–24.
</div>
<div id="ref-ripbergerCulturalTheoryMeasurement2014" class="csl-entry" role="listitem">
Ripberger, Joseph T., Kuhika Gupta, Carol L. Silva, and Hank C. Jenkins-Smith. 2014. <span>“Cultural <span>Theory</span> and the <span>Measurement</span> of <span>Deep Core Beliefs Within</span> the <span>Advocacy Coalition Framework</span>.”</span> <em>Policy Studies Journal</em> 42(4): 509–27.
</div>
<div id="ref-rosseelLavaanPackageStructural2012" class="csl-entry" role="listitem">
Rosseel, Yves. 2012. <span>“Lavaan: <span>An R</span> Package for <span>Structural Equation Modeling</span>.”</span> <em>Journal of Statistical Software</em> 48(2): 1–36.
</div>
<div id="ref-sabatierPolicyChangeLearning1993" class="csl-entry" role="listitem">
Sabatier, Paul A., and Hank C. Jenkins-Smith. 1993. <em>Policy <span>Change</span> and <span>Learning</span>: <span>An Advocacy Coalition Approach</span></em>. Boulder, CO: Westview Press.
</div>
<div id="ref-slimakPersonalValuesBeliefs2006" class="csl-entry" role="listitem">
Slimak, Michael W., and Thomas Dietz. 2006. <span>“Personal <span>Values</span>, <span>Beliefs</span>, and <span>Ecological Risk Perception</span>.”</span> <em>Risk Analysis</em> 26(6): 1689–1705.
</div>
<div id="ref-sotirovCognitiveTheoryShifting2016" class="csl-entry" role="listitem">
Sotirov, Metodi, and Georg Winkel. 2016. <span>“Toward a <span>Cognitive Theory</span> of <span>Shifting Coalitions</span> and <span>Policy Change</span>: <span>Linking</span> the <span>Advocacy Coalition Framework</span> and <span>Cultural Theory</span>.”</span> <em>Policy Sciences</em> 49(2): 125–54.
</div>
<div id="ref-sparksMeasuringProenvironmentalOrientation2022" class="csl-entry" role="listitem">
Sparks, Aaron C., Phillip J. Ehret, and Cameron Brick. 2022. <span>“Measuring <span>Pro-Environmental Orientation</span>: <span>Testing</span> and <span>Building Scales</span>.”</span> <em>Journal of Environmental Psychology</em> 81: 101780.
</div>
<div id="ref-sparksMeasuringEnvironmentalValues2021" class="csl-entry" role="listitem">
Sparks, Aaron C., Geoffrey L. Henderson, Shyam K. Sriram, and Eric R. A. N Smith. 2021. <span>“Measuring <span>Environmental Values</span> and <span>Identity</span>.”</span> <em>Society &amp; Natural Resources</em> 34(3): 291–310.
</div>
<div id="ref-stegGeneralAntecedentsPersonal2011" class="csl-entry" role="listitem">
Steg, Linda, Judith I. M. De Groot, Lieke Dreijerink, Wokje Abrahamse, and Frans Siero. 2011. <span>“General <span>Antecedents</span> of <span>Personal Norms</span>, <span>Policy Acceptability</span>, and <span>Intentions</span>: <span>The Role</span> of <span>Values</span>, <span>Worldviews</span>, and <span>Environmental Concern</span>.”</span> <em>Society &amp; Natural Resources</em> 24(4): 349–67.
</div>
<div id="ref-sternNewEnvironmentalTheories2000" class="csl-entry" role="listitem">
Stern, Paul C. 2000. <span>“New <span>Environmental Theories</span>: <span>Toward</span> a <span>Coherent Theory</span> of <span>Environmentally Significant Behavior</span>.”</span> <em>Journal of Social Issues</em> 56(3): 407–24.
</div>
<div id="ref-sternValueBasisEnvironmental1994" class="csl-entry" role="listitem">
Stern, Paul C., and Thomas Dietz. 1994. <span>“The <span>Value Basis</span> of <span>Environmental Concern</span>.”</span> <em>Journal of Social Issues</em> 50(3): 65–84.
</div>
<div id="ref-sternValueBeliefNormTheorySupport1999" class="csl-entry" role="listitem">
Stern, Paul C., Thomas Dietz, Troy D. Abel, Gregory A. Guagnano, and Linda Kalof. 1999. <span>“A <span>Value-Belief-Norm Theory</span> of <span>Support</span> for <span>Social Movements</span>: <span>The Case</span> of <span>Environmentalism</span>.”</span> <em>Human Ecology Review</em> 6(2): 81–97.
</div>
<div id="ref-sternNewEcologicalParadigm1995" class="csl-entry" role="listitem">
Stern, Paul C., Thomas Dietz, and Gregory A. Guagnano. 1995. <span>“The <span>New Ecological Paradigm</span> in <span>Social-Psychological Context</span>.”</span> <em>Environment and Behavior</em> 27(6): 723–43.
</div>
<div id="ref-thompsonCulturalTheory1990" class="csl-entry" role="listitem">
Thompson, Michael, Richard Ellis, and Aaron Wildavsky. 1990. <em>Cultural <span>Theory</span></em>. Boulder, CO: Westview Press.
</div>
<div id="ref-tumlisonWhatExplainsLocal2018" class="csl-entry" role="listitem">
Tumlison, Creed, Eric D. Button, Geoboo Song, and John Kester. 2018. <span>“What <span>Explains Local Policy Elites</span>’ <span>Preferences Toward Renewable Energy</span>/<span>Energy Efficiency Policy</span>?”</span> <em>Energy Policy</em> 117: 377–86.
</div>
<div id="ref-vysevkovaExplainingSupportEnvironmental2026" class="csl-entry" role="listitem">
Vysevkova, Violetta, Dominika Rabinska, Jason M. Thomas, Claire Farrow, and James Reynolds. 2026. <span>“Explaining <span>Support</span> for <span>Environmental Public Policies Through</span> the <span>Value-Belief-Norm Theory</span>: <span>A Systematic Review</span> with <span>Meta-Analysis</span>.”</span> <em>Journal of Environmental Psychology</em> 112: 103071.
</div>
<div id="ref-whitburnMetaanalysisHumanConnection2020" class="csl-entry" role="listitem">
Whitburn, Julie, Wayne Linklater, and Wokje Abrahamse. 2020. <span>“Meta-<span>Analysis</span> of <span>Human Connection</span> to <span>Nature</span> and <span>Proenvironmental Behavior</span>.”</span> <em>Conservation Biology</em> 34(1): 180–93.
</div>
<div id="ref-xiaoEcologicalWorldviewCentral2019" class="csl-entry" role="listitem">
Xiao, Chenyang, Riley E. Dunlap, and Dayong Hong. 2019. <span>“Ecological <span>Worldview</span> as the <span>Central Component</span> of <span>Environmental Concern</span>: <span>Clarifying</span> the <span>Role</span> of the <span>NEP</span>.”</span> <em>Society &amp; Natural Resources</em> 32(1): 53–72.
</div>
<div id="ref-xueCulturalWorldviewsEnvironmental2014" class="csl-entry" role="listitem">
Xue, Wen, Donald W. Hine, Natasha M. Loi, Einar B. Thorsteinsson, and Wendy J. Phillips. 2014. <span>“Cultural <span>Worldviews</span> and <span>Environmental Risk Perceptions</span>: <span>A Meta-Analysis</span>.”</span> <em>Journal of Environmental Psychology</em> 40.
</div>
<div id="ref-yeboahExplainingEnergyConservation2016" class="csl-entry" role="listitem">
Yeboah, Felix Kwame, and Michael D. Kaplowitz. 2016. <span>“Explaining <span>Energy Conservation</span> and <span>Environmental Citizenship Behaviors Using</span> the <span>Value-Belief-Norm Framework</span>.”</span> <em>Human Ecology Review</em> 22.
</div>
<div id="ref-zhuBibliometricVisualAnalysis2021" class="csl-entry" role="listitem">
Zhu, Chunkui, Peishan Tong, and Zhiping Song. 2021. <span>“A <span>Bibliometric</span> and <span>Visual Analysis</span> of <span>Environmental Behavior Research</span>.”</span> <em>Sustainability</em> 13(18): 10338.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>However, these authors also note that the CNS contains language that is more consistent with liberal environmentalism, and so may fail to adequately capture the full dimensionality of environmental support across the political spectrum <span class="citation" data-cites="brickUnearthingGreenPersonality2016">(<a href="#ref-brickUnearthingGreenPersonality2016" role="doc-biblioref">Brick and Lewis 2016</a>)</span>. Indeed, like the NEP, the CNS is composed mostly of items that tap into politically progressive environmentalism and thus may miss conservative pro-environmental orientation <span class="citation" data-cites="sparksMeasuringProenvironmentalOrientation2022">(<a href="#ref-sparksMeasuringProenvironmentalOrientation2022" role="doc-biblioref">Sparks, Ehret, and Brick 2022</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Our expectations and analyses are based on pro-environmental behaviors, overall. We do not distinguish between private or public behaviors.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The results of analyses that separates public and private are substantively the same as presented here.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>In the analysis we control for demographic variables, including age, gender (male=1), race (white=1), education, and income. We chose white males as the indicator variables because of the well-known <em>white-male effect</em> associated with risk perceptions and cultural cognition <span class="citation" data-cites="kahanCultureIdentityProtectiveCognition2007">(e.g., <a href="#ref-kahanCultureIdentityProtectiveCognition2007" role="doc-biblioref">Kahan et al. 2007</a>)</span>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>